### ISSUE TITLE
Not an issue but a question.

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [malthee/SimpleFileBackup#3]
Hello is it possible to have a second backup destination such as a network drive or a removable flash drive?

Joseph

**Comment by malthee** [comment]
Yes you can either select more folders at once in the GUI while holding CTRL or you can open the "Select folders" window multiple times. Also you can write the network path into the text field to add destinations.
Your selected output folders (flash drive, network drive) are saved in the "Backup Destinations" list. 

If you add a removable drive, you should watch out if the drive letter (ex. D:, E:, F:) changes the backup might not work anymore and you have to modify the list (either by selecting or deleting entries in "Backup Destinations"). 
Hope this helps
